apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      worker: web
  template:
    metadata:
      labels:
        worker: web
    spec:
      containers:
        - name: worker
          image: pts/worker:latest
          imagePullPolicy: Never
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: worker
#  namespace: default
#spec:
#  type: NodePort
#  selector:
#    pts-worker: web
#  ports:
#    - port: 8083
#      targetPort: 8083
#      nodePort: 30003


apiVersion: v1
kind: Service
metadata:
  name: busybox-subdomain
spec:
  selector:
    name: busybox
  clusterIP: None
  ports:
    - name: foo # name is not required for single-port Services
      port: 1234
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    name: busybox
spec:
  hostname: busybox-1
  subdomain: busybox-subdomain
  containers:
    - image: busybox:1.28
      command:
        - sleep
        - "3600"
      name: busybox
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  labels:
    name: busybox
spec:
  hostname: busybox-2
  subdomain: busybox-subdomain
  containers:
    - image: busybox:1.28
      command:
        - sleep
        - "3600"
      name: busybox